### ISSUE TITLE
servo issue

### ISSUE THREAD

**Issue by Ahmed-Dakrory** [vjaunet/QUADCOPTER#2]
does you send the signal to the ESC direct or you use some interface between RPI and ESC in V1 and this video https://www.youtube.com/watch?v=cc01GgzKo0c is V1 or V2 and if you use the servo plaster direct does the quad will work good like which you have :) and thanks .

**Comment by Ahmed-Dakrory** [comment]
i have work for a quad with arduino uno and it work good but what make me go to RPI that the DMP hanging and i dont know why so when i use servo plaster to my quad with the same algorithm it doesnt make useful response and i have tuning it for 4 hours with no result does this from servo plaster PWM or what do you think. (please help as you can )

**Comment by vjaunet** [comment]
Hi,
The ESCs are directly connected to the RPI in V1, the servoblaster library generates the PWM signals.

ESCs have to be calibrated before running. You can use what is in the SERVOS folder to calibrate them. That could be an issue.

DMP hanging is another thing, it could be due to the fact that you don't read the output buffer fast enough. You may have to deal with the DMP sampling frequency to match it with your main loop one.

Hope this helps,
VIncent

**Comment by Ahmed-Dakrory** [comment]
first thanks at all and i have another question how do you get the supply voltage to the RPI do you use the same battery or another battery of the brushless and do you use voltage regulator or what (thanks)

**Comment by vjaunet** [comment]
Hi,
I am using a switching regulator based on a LM2596. see http://www.daveakerman.com/?page_id=1294.
I also tried using a 7805 regulator or the BEC that are inside the ESCs. Both technique suffered from the current draw of the Pi, and the linear regulators got really hot : about 7W of heat need to be dissipated and thus you need to use radiators. That is why I went for the LM2596.

Regards,
Vincent

**Comment by Ahmed-Dakrory** [comment]
thanks man but i see in the video that you connect the rasperrypi power with the cable of the usb do you change it or what is this :)

**Comment by vjaunet** [comment]
FYI, this video is not mine but they used the code that I shared.
It is up to you to decide how to power the RPi. Using the microUSB plug is a safe idea since it is protected (fuses etc.), contrary to the GPIO pins.
You can use a switching regluator that you connect to a USB cable plugged in the RPi fex.

Regards,
Vincent

**Comment by Ahmed-Dakrory** [comment]
do have any idea about connecting mcroUSB through the battary :)

**Comment by vjaunet** [comment]
http://www.leadsdirect.co.uk/technical-library/pinouts-wiring-diagrams/usb-wiring/
;-)

**Comment by Ahmed-Dakrory** [comment]
thanks a lot and i hope more good work thanks :)

**Comment by Ahmed-Dakrory** [comment]
i have wonder what make you use arduino in the V2 is it because servo blaster not good or what

**Comment by gregd72002** [comment]
Lol, I see you had similar idea to use arduino :) Though I think our approach is slightly different:
https://github.com/rpicopter/AvrMiniCopter

I’m very confident this is the way to go to get a quadcopter with super stable flight :) and plenty of power to do other stuff.

Good luck!

**Comment by vjaunet** [comment]
In the v1, I wanted to do everything on the pi so that very few else electronic or cabling would be necessary. I made it fly, very stable.
Then, for the next evolution I wanted to use a real RC transmitter for more comfortable control. That is why I used an arduino, the RPi would not allow me to precisely measure pwm signals coming from a receiver.

Thanks for the link Greg. It is true that our solutions are very similar. I like your idea of the Pi being a somehow universal RC decoder that transmit commands to the arduino.

I believe that the most convenient for precise flight is to use an RC transmission, except if you want to go for autonomous flights, which I don't yet. Therefore everything could be hosted on an arduino, the RPi would then be a powerful flying computer :-)

Cheers

**Comment by Ahmed-Dakrory** [comment]
thanks a lot man wait me for good quad with another thing i will use image processing with it with different technique. :) thanks

**Comment by Ashok0111** [comment]
hi, i am working on Quadcopter v1 , i have an issue hope u could solve this and help me out of this issue.while calibrating esc's i dont get any beep sound here, and what are the servo blaster configuration , I am using raspberry pi 3. Please help me and make my quad fly :)
 Thanks alot.
